# see the GitHub - Dependabot version updates documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    labels:
      - "pip"
      - "dependencies"
    open-pull-requests-limit: 2
    reviewers:
      - "dpgraham4401"
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "monthly"
    labels:
      - "pip"
      - "dependencies"
    open-pull-requests-limit: 2
    reviewers:
      - "dpgraham4401"
